'use client'

import { useEffect, useState } from 'react'
import { useSession } from 'next-auth/react'

type Learner = { id: string; name: string; email: string; accessLevel: 'free' | 'paid'; isAdmin: boolean }

export default function AdminPage() {
  const { data: session, status } = useSession(); const [learners, setLearners] = useState<Learner[]>([]); const [error, setError] = useState('')
  useEffect(() => { if (session?.user?.isAdmin) fetch('/api/admin/users').then(async (r) => { const data = await r.json(); if (!r.ok) setError(data.error); else setLearners(data.users) }) }, [session?.user?.isAdmin])
  async function changeAccess(id: string, accessLevel: 'free' | 'paid') { const response = await fetch('/api/admin/users', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id, accessLevel }) }); if (response.ok) setLearners((current) => current.map((user) => user.id === id ? { ...user, accessLevel } : user)) }
  if (status === 'loading') return <main className="p-8 text-[#153b32]">Chargement...</main>
  if (!session?.user?.isAdmin) return <main className="flex min-h-screen items-center justify-center bg-[#f7faf8] p-6 text-center text-[#153b32]"><div><h1 className="font-serif text-3xl font-bold">Accès refusé</h1><p className="mt-2 text-[#6b8179]">Cette page est réservée à l&apos;administrateur.</p><a href="/login" className="mt-5 inline-block font-bold text-[#006a4e]">Se connecter</a></div></main>
  return <main className="min-h-screen bg-[#f7faf8] px-5 py-10 text-[#153b32] lg:px-10"><div className="mx-auto max-w-6xl"><a href="/" className="text-sm font-bold text-[#006a4e]">← Retour aux formations</a><div className="mt-6 flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#008263]">Administration</p><h1 className="mt-2 font-serif text-4xl font-bold">Gestion des apprenants</h1><p className="mt-2 text-[#6b8179]">Consultez les comptes et ajustez leur niveau d&apos;accès.</p></div><div className="rounded-2xl bg-white px-5 py-4 shadow-sm"><p className="text-2xl font-bold">{learners.length}</p><p className="text-xs font-semibold text-[#6b8179]">comptes enregistrés</p></div></div>{error && <p className="mt-6 rounded-xl bg-[#fff1ef] p-3 font-semibold text-[#a33d32]">{error}</p>}<div className="mt-8 overflow-x-auto rounded-2xl border border-[#dcebe4] bg-white"><table className="w-full min-w-[650px] text-left text-sm"><thead className="border-b border-[#e8f0ec] text-xs uppercase tracking-wider text-[#71877e]"><tr><th className="px-5 py-4">Apprenant</th><th className="px-5 py-4">Email</th><th className="px-5 py-4">Accès</th><th className="px-5 py-4">Action</th></tr></thead><tbody className="divide-y divide-[#edf2ef]">{learners.map((learner) => <tr key={learner.id}><td className="px-5 py-4 font-bold">{learner.name}{learner.isAdmin && <span className="ml-2 rounded-full bg-[#e5f3eb] px-2 py-1 text-[10px] text-[#006a4e]">Admin</span>}</td><td className="px-5 py-4 text-[#6b8179]">{learner.email}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${learner.accessLevel === 'paid' ? 'bg-[#fff1d9] text-[#936319]' : 'bg-[#e2f3e8] text-[#21734c]'}`}>{learner.accessLevel === 'paid' ? 'Premium' : 'Gratuit'}</span></td><td className="px-5 py-4"><select value={learner.accessLevel} onChange={(e) => void changeAccess(learner.id, e.target.value as 'free' | 'paid')} className="rounded-lg border border-[#d4e5dd] bg-white px-3 py-2 font-semibold"><option value="free">Gratuit</option><option value="paid">Premium</option></select></td></tr>)}</tbody></table></div></div></main>
}
