'use client'

import { useState } from 'react'
import { ArrowRight, BookOpen, CheckCircle2, ChevronDown, Clock3, Edit3, Eye, LayoutDashboard, LockKeyhole, LogIn, Menu, PlayCircle, Plus, Search, ShieldCheck, Sparkles, Users, X } from 'lucide-react'

const courses = [
  { id: 1, title: 'Créer sa première vidéo avec l’IA', category: 'Vidéo IA', description: 'De l’idée au premier montage : découvrez les outils essentiels et créez une vidéo pas à pas.', duration: '24 min', lessons: 5, level: 'Débutant', free: true, accent: 'emerald' },
  { id: 2, title: 'Écrire un script vidéo avec l’IA', category: 'Écriture créative', description: 'Transformez une idée en script clair, accrocheur et prêt à être mis en images.', duration: '31 min', lessons: 6, level: 'Intermédiaire', free: true, accent: 'teal' },
  { id: 3, title: 'Générer des images et des scènes', category: 'Image IA', description: 'Créez des visuels cohérents et apprenez à les transformer en scènes pour votre vidéo.', duration: '42 min', lessons: 8, level: 'Intermédiaire', free: false, accent: 'olive' },
  { id: 4, title: 'Animer une image avec l’IA', category: 'Animation IA', description: 'Donnez vie à vos images avec des mouvements, des transitions et des effets simples.', duration: '38 min', lessons: 7, level: 'Avancé', free: false, accent: 'forest' },
  { id: 5, title: 'Créer une voix off et une musique', category: 'Animation IA', description: 'Ajoutez une narration naturelle et une ambiance sonore adaptée à votre création.', duration: '28 min', lessons: 5, level: 'Avancé', free: false, accent: 'green' },
  { id: 6, title: 'Monter et publier sa vidéo IA', category: 'Vidéo IA', description: 'Assemblez vos séquences, peaufinez le montage et préparez votre vidéo pour la partager.', duration: '35 min', lessons: 6, level: 'Débutant', free: false, accent: 'sage' },
]

export default function Home() {
  const [view, setView] = useState<'catalog' | 'admin'>('catalog')
  const [query, setQuery] = useState('')
  const [selected, setSelected] = useState<typeof courses[number] | null>(null)
  const [menuOpen, setMenuOpen] = useState(false)
  const filtered = courses.filter((course) => `${course.title} ${course.category}`.toLowerCase().includes(query.toLowerCase()))

  return <main className="min-h-screen bg-[#f7faf8] text-[#153b32]">
    <header className="sticky top-0 z-30 border-b border-[#dcebe4] bg-[#f7faf8]/95 backdrop-blur">
      <div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-3 lg:px-8">
        <button onClick={() => { setView('catalog'); setMenuOpen(false) }} className="flex items-center gap-3" aria-label="Retour à l'accueil">
          <img src="/assar-logo.png" alt="Logo ASSAR" className="size-12 object-contain" />
          <div className="hidden sm:block text-left"><p className="font-serif text-lg font-bold tracking-tight text-[#005b46]">ASSAR</p><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-[#6d877e]">IA créative</p></div>
        </button>
        <nav className="hidden items-center gap-7 md:flex"><button onClick={() => setView('catalog')} className={`text-sm font-semibold ${view === 'catalog' ? 'text-[#006a4e]' : 'text-[#61776f] hover:text-[#006a4e]'}`}>Formations</button><a href="#about" className="text-sm font-semibold text-[#61776f] hover:text-[#006a4e]">À propos</a><a href="#contact" className="text-sm font-semibold text-[#61776f] hover:text-[#006a4e]">Contact</a></nav>
        <div className="flex items-center gap-2"><button onClick={() => setView('admin')} className="hidden rounded-full px-4 py-2 text-sm font-semibold text-[#006a4e] hover:bg-[#e7f2ed] sm:block">Espace admin</button><button onClick={() => setSelected(courses[2])} className="flex items-center gap-2 rounded-full bg-[#006a4e] px-4 py-2.5 text-sm font-bold text-white shadow-sm hover:bg-[#00563f]"><LogIn data-icon="inline-start" /> Se connecter</button><button className="rounded-lg p-2 md:hidden" onClick={() => setMenuOpen(!menuOpen)} aria-label="Menu">{menuOpen ? <X /> : <Menu />}</button></div>
      </div>
      {menuOpen && <div className="border-t border-[#dcebe4] px-5 py-4 md:hidden"><div className="flex flex-col gap-4 text-sm font-semibold"><button className="text-left" onClick={() => { setView('catalog'); setMenuOpen(false) }}>Formations</button><a href="#about" onClick={() => setMenuOpen(false)}>À propos</a><button className="text-left text-[#006a4e]" onClick={() => { setView('admin'); setMenuOpen(false) }}>Espace admin</button></div></div>}
    </header>

    {view === 'admin' ? <AdminView onBack={() => setView('catalog')} /> : <>
      <section className="relative overflow-hidden bg-[#e8f4ef]">
        <div className="mx-auto grid max-w-7xl items-center gap-10 px-5 py-14 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:py-20"><div><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-[#b9d9ca] bg-white/70 px-3 py-1.5 text-xs font-bold uppercase tracking-[.12em] text-[#006a4e]"><Sparkles data-icon="inline-start" /> Créez avec l’IA, simplement</div><h1 className="max-w-2xl font-serif text-4xl font-bold leading-[1.08] tracking-tight text-[#123e32] sm:text-5xl lg:text-6xl">L’IA créative,<br /><span className="text-[#008263]">de l’idée à la vidéo.</span></h1><p className="mt-6 max-w-xl text-base leading-7 text-[#55736a] sm:text-lg">Des formations vidéo courtes et pratiques pour débuter avec les outils d’IA créative et réaliser votre propre vidéo de A à Z.</p><div className="mt-8 flex flex-wrap gap-3"><button onClick={() => document.getElementById('formations')?.scrollIntoView({ behavior: 'smooth' })} className="flex items-center gap-2 rounded-full bg-[#006a4e] px-5 py-3 text-sm font-bold text-white shadow-lg shadow-[#006a4e]/15 hover:bg-[#00563f]">Découvrir les formations <ArrowRight data-icon="inline-end" /></button><button onClick={() => setSelected(courses[0])} className="rounded-full border border-[#b9d9ca] bg-white/70 px-5 py-3 text-sm font-bold text-[#006a4e] hover:bg-white">Voir le cours gratuit</button></div><div className="mt-9 flex items-center gap-6 text-sm text-[#55736a]"><span className="flex items-center gap-2"><CheckCircle2 className="text-[#008263]" /> 2 cours gratuits</span><span className="flex items-center gap-2"><ShieldCheck className="text-[#008263]" /> Pensé pour débuter</span></div></div><div className="relative mx-auto w-full max-w-lg"><div className="absolute -right-4 -top-5 size-28 rounded-full bg-[#cbe7d8] blur-2xl" /><div className="relative overflow-hidden rounded-[2rem] border-8 border-white bg-[#005b46] p-5 shadow-2xl shadow-[#1a5847]/20"><div className="flex items-center justify-between text-white/70"><span className="text-xs font-bold uppercase tracking-widest">ASSAR • IA créative</span><span className="rounded-full bg-white/15 px-2 py-1 text-xs">01 / 06</span></div><div className="mt-16 flex aspect-video items-center justify-center rounded-2xl bg-gradient-to-br from-[#0e8067] to-[#003e32]"><button onClick={() => setSelected(courses[0])} className="flex size-16 items-center justify-center rounded-full bg-white text-[#006a4e] shadow-xl transition hover:scale-105" aria-label="Lire la vidéo gratuite"><PlayCircle className="size-8 fill-[#dff4e8]" /></button></div><div className="mt-5"><div className="mb-2 h-1.5 rounded-full bg-white/20"><div className="h-full w-1/3 rounded-full bg-[#a9dfbf]" /></div><p className="text-sm font-semibold text-white">Créer sa première vidéo avec l’IA</p><p className="mt-1 text-xs text-white/60">Introduction • 04:12</p></div></div></div></div>
      </section>

      <section id="formations" className="mx-auto max-w-7xl px-5 py-14 lg:px-8 lg:py-20"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="mb-2 text-xs font-bold uppercase tracking-[.18em] text-[#008263]">Notre catalogue</p><h2 className="font-serif text-3xl font-bold tracking-tight text-[#153b32] sm:text-4xl">Apprenez à votre rythme</h2><p className="mt-3 max-w-xl text-[#69827a]">Des vidéos courtes et pratiques pour apprendre à créer avec les outils d’IA.</p></div><div className="relative w-full sm:max-w-xs"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-[#779087]" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Rechercher une formation..." className="w-full rounded-xl border border-[#d4e5dd] bg-white py-3 pl-10 pr-4 text-sm outline-none ring-[#8bc6a9] focus:ring-2" /></div></div><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{filtered.map((course, index) => <article key={course.id} className="group flex flex-col overflow-hidden rounded-2xl border border-[#deebe5] bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl hover:shadow-[#164f3b]/10"><div className={`relative flex h-40 items-center justify-center overflow-hidden bg-gradient-to-br ${index % 3 === 0 ? 'from-[#0b765c] to-[#b6dec6]' : index % 3 === 1 ? 'from-[#087d78] to-[#b9e4d7]' : 'from-[#31684b] to-[#d8e7c4]'}`}><div className="absolute inset-0 opacity-20" style={{ backgroundImage: 'radial-gradient(#fff 1px, transparent 1px)', backgroundSize: '18px 18px' }} /><span className="relative rounded-full bg-white/90 p-4 text-[#006a4e] shadow-lg"><PlayCircle className="size-8" /></span><span className="absolute left-4 top-4 rounded-full bg-white/90 px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider text-[#006a4e]">{course.category}</span>{course.free ? <span className="absolute right-4 top-4 rounded-full bg-[#d9f2df] px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider text-[#21734c]">Gratuit</span> : <span className="absolute right-4 top-4 rounded-full bg-[#153b32]/80 px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider text-white">Premium</span>}</div><div className="flex flex-1 flex-col p-5"><h3 className="font-serif text-xl font-bold text-[#153b32]">{course.title}</h3><p className="mt-2 flex-1 text-sm leading-6 text-[#6b8179]">{course.description}</p><div className="mt-5 flex items-center justify-between border-t border-[#edf2ef] pt-4 text-xs font-semibold text-[#82958e]"><span className="flex items-center gap-1.5"><Clock3 /> {course.duration}</span><span>{course.lessons} leçons</span><button onClick={() => setSelected(course)} className="text-[#006a4e] hover:underline">Voir le cours <ArrowRight className="inline" /></button></div></div></article>)}</div></section>
      <section id="about" className="border-y border-[#dcebe4] bg-white"><div className="mx-auto grid max-w-7xl gap-8 px-5 py-12 sm:grid-cols-3 lg:px-8"><div><div className="mb-3 flex size-10 items-center justify-center rounded-xl bg-[#e5f3eb] text-[#006a4e]"><BookOpen /></div><h3 className="font-bold">Des formats courts</h3><p className="mt-2 text-sm leading-6 text-[#6b8179]">Des vidéos claires et des explications pas à pas pour apprendre en faisant.</p></div><div><div className="mb-3 flex size-10 items-center justify-center rounded-xl bg-[#e5f3eb] text-[#006a4e]"><Users /></div><h3 className="font-bold">Pour les débutants</h3><p className="mt-2 text-sm leading-6 text-[#6b8179]">Découvrez les outils d’IA créative sans prérequis et avancez à votre rythme.</p></div><div><div className="mb-3 flex size-10 items-center justify-center rounded-xl bg-[#e5f3eb] text-[#006a4e]"><ShieldCheck /></div><h3 className="font-bold">De l’idée à la vidéo</h3><p className="mt-2 text-sm leading-6 text-[#6b8179]">Suivez un projet concret de A à Z : scénario, images, voix, montage et partage.</p></div></div></section>
    </>}

    {selected && <CourseModal course={selected} onClose={() => setSelected(null)} />}
  </main>
}

function CourseModal({ course, onClose }: { course: typeof courses[number], onClose: () => void }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#0b2c24]/60 p-4 backdrop-blur-sm" onClick={onClose}><div className="w-full max-w-4xl overflow-hidden rounded-3xl bg-white shadow-2xl" onClick={(e) => e.stopPropagation()}><div className="flex items-center justify-between border-b border-[#e1ece7] px-5 py-4"><div><p className="text-xs font-bold uppercase tracking-wider text-[#008263]">{course.category}</p><h2 className="font-serif text-xl font-bold text-[#153b32]">{course.title}</h2></div><button onClick={onClose} className="rounded-full p-2 text-[#6b8179] hover:bg-[#eef6f1]" aria-label="Fermer"><X /></button></div><div className="grid lg:grid-cols-[1.25fr_.75fr]"><div className="bg-[#092e25] p-4 sm:p-6"><div className="flex aspect-video items-center justify-center rounded-2xl bg-gradient-to-br from-[#0e8067] to-[#002e25]"><div className="text-center text-white"><button className="mx-auto flex size-16 items-center justify-center rounded-full bg-white text-[#006a4e] shadow-xl" aria-label="Lire la vidéo"><PlayCircle className="size-8 fill-[#dff4e8]" /></button><p className="mt-4 text-sm font-semibold">{course.free ? 'La vidéo est disponible' : 'Aperçu de la formation'}</p></div></div></div><div className="p-5 sm:p-6"><div className="flex items-center justify-between"><span className="rounded-full bg-[#e2f3e8] px-2.5 py-1 text-xs font-bold text-[#21734c]">{course.free ? 'Accès gratuit' : 'Formation premium'}</span><span className="text-xs font-semibold text-[#81948d]">{course.duration}</span></div><h3 className="mt-5 font-serif text-2xl font-bold text-[#153b32]">À propos de ce cours</h3><p className="mt-3 text-sm leading-6 text-[#6b8179]">{course.description} Retrouvez une explication détaillée à côté de chaque vidéo pour progresser facilement.</p>{!course.free && <div className="mt-5 flex items-start gap-3 rounded-xl bg-[#fff8e8] p-3 text-sm text-[#7d682d]"><LockKeyhole className="mt-0.5 shrink-0" /> Connectez-vous pour accéder à cette formation.</div>}<button onClick={() => { if (!course.free) { onClose(); } }} className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-[#006a4e] py-3 text-sm font-bold text-white hover:bg-[#00563f]">{course.free ? 'Commencer la formation' : 'Se connecter pour continuer'} <ArrowRight /></button></div></div></div></div> }

function AdminView({ onBack }: { onBack: () => void }) { return <section className="mx-auto max-w-7xl px-5 py-10 lg:px-8"><div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><button onClick={onBack} className="mb-5 text-sm font-bold text-[#006a4e]">← Retour au catalogue</button><p className="text-xs font-bold uppercase tracking-[.18em] text-[#008263]">Administration</p><h1 className="mt-2 font-serif text-4xl font-bold tracking-tight">Bonjour, équipe ASSAR</h1><p className="mt-2 text-[#6b8179]">Gérez vos formations et suivez votre communauté.</p></div><button className="flex items-center justify-center gap-2 rounded-xl bg-[#006a4e] px-4 py-3 text-sm font-bold text-white"><Plus /> Ajouter une formation</button></div><div className="grid gap-4 sm:grid-cols-3"><Stat icon={<BookOpen />} label="Formations publiées" value="06" /><Stat icon={<Users />} label="Utilisateurs inscrits" value="128" /><Stat icon={<Eye />} label="Vues ce mois" value="2 846" /></div><div className="mt-8 overflow-hidden rounded-2xl border border-[#dcebe4] bg-white"><div className="flex items-center justify-between border-b border-[#e8f0ec] px-5 py-4"><h2 className="font-serif text-xl font-bold">Vos formations</h2><button className="text-sm font-bold text-[#006a4e]">Voir tout</button></div><div className="divide-y divide-[#edf2ef]">{courses.slice(0, 4).map((course) => <div key={course.id} className="flex flex-col gap-3 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><div className="flex size-11 items-center justify-center rounded-xl bg-[#e5f3eb] text-[#006a4e]"><PlayCircle /></div><div><p className="font-bold text-[#153b32]">{course.title}</p><p className="mt-1 text-xs text-[#80948c]">{course.lessons} leçons · {course.duration}</p></div></div><div className="flex items-center gap-3 pl-14 sm:pl-0"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${course.free ? 'bg-[#e2f3e8] text-[#21734c]' : 'bg-[#f1ead8] text-[#866d2e]'}`}>{course.free ? 'Gratuit' : 'Premium'}</span><button className="rounded-lg p-2 text-[#71877e] hover:bg-[#eef6f1]" aria-label={`Modifier ${course.title}`}><Edit3 /></button></div></div>)}</div></div></section> }
function Stat({ icon, label, value }: { icon: React.ReactNode, label: string, value: string }) { return <div className="rounded-2xl border border-[#dcebe4] bg-white p-5"><div className="flex items-center justify-between"><span className="flex size-10 items-center justify-center rounded-xl bg-[#e5f3eb] text-[#006a4e]">{icon}</span><span className="text-2xl font-bold text-[#153b32]">{value}</span></div><p className="mt-4 text-sm font-semibold text-[#71877e]">{label}</p></div> }
